using UnityEngine;
using UnityEngine.UIElements;

namespace Cdm.Figma.UIToolkit
{
	// This code was generated by a machine from UnityEngine.UIElements.IStyle.
	public partial class Style
	{
		public StyleEnum<Align>? alignContent { get; set; } = null;
		public StyleEnum<Align>? alignItems { get; set; } = null;
		public StyleEnum<Align>? alignSelf { get; set; } = null;
		public StyleColor? backgroundColor { get; set; } = null;
		public StyleBackground? backgroundImage { get; set; } = null;
		public StyleColor? borderBottomColor { get; set; } = null;
		public StyleLength? borderBottomLeftRadius { get; set; } = null;
		public StyleLength? borderBottomRightRadius { get; set; } = null;
		public StyleFloat? borderBottomWidth { get; set; } = null;
		public StyleColor? borderLeftColor { get; set; } = null;
		public StyleFloat? borderLeftWidth { get; set; } = null;
		public StyleColor? borderRightColor { get; set; } = null;
		public StyleFloat? borderRightWidth { get; set; } = null;
		public StyleColor? borderTopColor { get; set; } = null;
		public StyleLength? borderTopLeftRadius { get; set; } = null;
		public StyleLength? borderTopRightRadius { get; set; } = null;
		public StyleFloat? borderTopWidth { get; set; } = null;
		public StyleLength? bottom { get; set; } = null;
		public StyleColor? color { get; set; } = null;
		public StyleCursor? cursor { get; set; } = null;
		public StyleEnum<DisplayStyle>? display { get; set; } = null;
		public StyleLength? flexBasis { get; set; } = null;
		public StyleEnum<FlexDirection>? flexDirection { get; set; } = null;
		public StyleFloat? flexGrow { get; set; } = null;
		public StyleFloat? flexShrink { get; set; } = null;
		public StyleEnum<Wrap>? flexWrap { get; set; } = null;
		public StyleLength? fontSize { get; set; } = null;
		public StyleLength? height { get; set; } = null;
		public StyleEnum<Justify>? justifyContent { get; set; } = null;
		public StyleLength? left { get; set; } = null;
		public StyleLength? letterSpacing { get; set; } = null;
		public StyleLength? marginBottom { get; set; } = null;
		public StyleLength? marginLeft { get; set; } = null;
		public StyleLength? marginRight { get; set; } = null;
		public StyleLength? marginTop { get; set; } = null;
		public StyleLength? maxHeight { get; set; } = null;
		public StyleLength? maxWidth { get; set; } = null;
		public StyleLength? minHeight { get; set; } = null;
		public StyleLength? minWidth { get; set; } = null;
		public StyleFloat? opacity { get; set; } = null;
		public StyleEnum<Overflow>? overflow { get; set; } = null;
		public StyleLength? paddingBottom { get; set; } = null;
		public StyleLength? paddingLeft { get; set; } = null;
		public StyleLength? paddingRight { get; set; } = null;
		public StyleLength? paddingTop { get; set; } = null;
		public StyleEnum<Position>? position { get; set; } = null;
		public StyleLength? right { get; set; } = null;
		public StyleRotate? rotate { get; set; } = null;
		public StyleScale? scale { get; set; } = null;
		public StyleEnum<TextOverflow>? textOverflow { get; set; } = null;
		public StyleTextShadow? textShadow { get; set; } = null;
		public StyleLength? top { get; set; } = null;
		public StyleTransformOrigin? transformOrigin { get; set; } = null;
		public StyleList<TimeValue>? transitionDelay { get; set; } = null;
		public StyleList<TimeValue>? transitionDuration { get; set; } = null;
		public StyleList<StylePropertyName>? transitionProperty { get; set; } = null;
		public StyleList<EasingFunction>? transitionTimingFunction { get; set; } = null;
		public StyleTranslate? translate { get; set; } = null;
		public StyleColor? unityBackgroundImageTintColor { get; set; } = null;
		public StyleEnum<ScaleMode>? unityBackgroundScaleMode { get; set; } = null;
		public StyleFont? unityFont { get; set; } = null;
		public StyleFontDefinition? unityFontDefinition { get; set; } = null;
		public StyleEnum<FontStyle>? unityFontStyleAndWeight { get; set; } = null;
		public StyleEnum<OverflowClipBox>? unityOverflowClipBox { get; set; } = null;
		public StyleLength? unityParagraphSpacing { get; set; } = null;
		public StyleInt? unitySliceBottom { get; set; } = null;
		public StyleInt? unitySliceLeft { get; set; } = null;
		public StyleInt? unitySliceRight { get; set; } = null;
		public StyleInt? unitySliceTop { get; set; } = null;
		public StyleEnum<TextAnchor>? unityTextAlign { get; set; } = null;
		public StyleColor? unityTextOutlineColor { get; set; } = null;
		public StyleFloat? unityTextOutlineWidth { get; set; } = null;
		public StyleEnum<TextOverflowPosition>? unityTextOverflowPosition { get; set; } = null;
		public StyleEnum<Visibility>? visibility { get; set; } = null;
		public StyleEnum<WhiteSpace>? whiteSpace { get; set; } = null;
		public StyleLength? width { get; set; } = null;
		public StyleLength? wordSpacing { get; set; } = null;
	}
}
